name: Main
on:
  push:
    paths-ignore:
      - "**.md"

permissions:
  contents: read
  checks: write
  pages: write
  id-token: write

jobs:
  build_image:
    uses: CubicrootXYZ/Workflows/.github/workflows/build_image.yaml@v0.0.20
    with:
      docker_build_args: "--no-cache"
      docker_file_path: "./"
      image_name: "cubicrootxyz/files-to-webdav"
      static_tag: "beta"
      vuln_scan: false
    secrets:
      dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
